[package]
name = "pg_snowid"
version = "3.2.3"
edition = "2024"
resolver = "3"
rust-version = "1.96"

authors = ["Maksim Sosnovskii <maksim@rixl.com>"]
description = "Generate Snowflake-like IDs with speed and thread-safety in PostgreSQL"

license = "MIT"
readme = "README.md"
keywords = ["snowflake", "id", "uuid", "postgres", "pgrx"]
categories = ["database"]

documentation = "https://github.com/qeeqez/snowid-postgres"
homepage = "https://github.com/qeeqez/snowid-postgres"
repository = "https://github.com/qeeqez/snowid-postgres"

[lib]
crate-type = ["cdylib"]


[features]
default = ["pg18"]
pg18 = ["pgrx/pg18", "pgrx-tests/pg18"]

pg_test = []

[dependencies]
pgrx = "0.19.2"
snowid = "3.0.1"
heapless = "0.9.3"

[dev-dependencies]
pgrx-tests = "0.19.2"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = true
codegen-units = 1

[lints.rust]
unused_qualifications = "deny"
unused_allocation = "deny"
redundant_semicolons = "deny"

[lints.clippy]
pedantic = "warn"
panic = "warn"
print_stdout = "warn"
print_stderr = "warn"
cognitive_complexity = "warn"
too_many_lines = "warn"
cast_possible_truncation = "warn"
cast_possible_wrap = "warn"
cast_precision_loss = "warn"
cast_sign_loss = "warn"
checked_conversions = "warn"
